AllCops:
  Exclude:
    - Guardfile
    - 'vendor/**/*'

Metrics/LineLength:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
Style/SpaceBeforeFirstArg:
  Enabled: false
Style/ExtraSpacing:
  Enabled: false